### ISSUE TITLE
import usb.core fails with "No module named core"

### ISSUE THREAD

**Issue by jzacsh** [braiden/python-ant-downloader#43]
Strangely I get this error:

``` bash
$ git checkout master
$ git pull origin master
$ ./ant-downloader.py
Traceback (most recent call last):
  File "./ant-downloader.py", line 2, in <module>
    from antd.main import downloader
  File "/home/jzacsh/tmp/src/python-ant-downloader/antd/__init__.py", line 35, in <module>
    import antd.hw as hw
  File "/home/jzacsh/tmp/src/python-ant-downloader/antd/hw.py", line 30, in <module>
    import usb.core
ImportError: No module named core

# _(same when I prefix with `PYTHON= ` to ensure its not an env. issue)_
```

[Seems like its probably](http://stackoverflow.com/questions/6213361) my fault _(bad env.?)_, but figured I'd put this issue out, until I'm sure _(feel free to close this if you have no thoughts on the matter)_....

Some more info (previously, I ran `sudo apt-get install python-usb` for package version 0.4.3-1):

```
$ python --version
Python 2.7.3

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.10
DISTRIB_CODENAME=quantal
DISTRIB_DESCRIPTION="Ubuntu 12.10"

$ locate usb | grep py
/usr/lib/pyshared/python2.7/usb.so
# ....
```

Any thoughts on what might be going on?

**Comment by mckaygerhard** [comment]
stupid non-debian-way the right solution using the system-wide are backporting the pyusb package from unstable.. 

* debian, winbuntu winhat default python usb modulo is << 1.0 that has full of bugs

* soluciton is use backporting or from unstalbe:

1) revise you have an entry of backport in apt sources list:
`deb deb http://ftp.de.debian.org/debian jessie-backports main contrib non-free`
*NOTE* can do this as: 
`echo "deb deb http://ftp.de.debian.org/debian jessie-backports main contrib non-free" > /etc/apt/sources.list.d/backports.list`
2) update apt database:
`apt-get update`
3) install from backport forced:
`apt-get install -t backports python-usb`

the other way (in that time, when backport still not have it the package) was downloading manually from unstalble and install manually using dpkg, that's all
