### ISSUE TITLE
uploads to the new Garmin Connect don't appear on the website

### ISSUE THREAD

**Issue by mhl** [braiden/python-ant-downloader#66]
First of all, thank-you very much for this excellent project, which means I can get files off my Garmin Forerunner 410 despite only having Linux-based computers!

One problem, however, is that since Garmin redesigned their website, the upload to the website still appears to work, but the files never appear in "Activities". I have to subsequently upload the `.tcx` files manually. For example, here's the end of the terminal output where a file is apparently uploaded without error:

```
...
[MainThread]	2015-07-18 09:55:55,267	INFO	tcx: writing 20150718-095538.raw -> /home/mark/.antd/0xe579eb79/tcx/20150718-080513.tcx.
[MainThread]	2015-07-18 09:55:55,290	DEBUG	Checking to see what style of login to use for Garmin Connect.
Waiting for lock
Have lock
Rate limited
[MainThread]	2015-07-18 09:55:56,582	DEBUG	Using new style login
[MainThread]	2015-07-18 09:55:56,582	DEBUG	Fetching login variables
[MainThread]	2015-07-18 09:55:57,068	DEBUG	lt=e1s1
[MainThread]	2015-07-18 09:55:57,068	DEBUG	Posting login credentials to Garmin Connect. username=mark.longair
[MainThread]	2015-07-18 09:55:57,610	DEBUG	Post login step 1
Waiting for lock
Have lock
Rate limited
[MainThread]	2015-07-18 09:55:58,835	DEBUG	Post login step 2
Waiting for lock
Have lock
Rate limited
[MainThread]	2015-07-18 09:56:00,166	INFO	Uploading /home/mark/.antd/0xe579eb79/tcx/20150718-080513.tcx to Garmin Connect.
$
```

But it doesn't appear in my activities:

![garmin-connect](https://cloud.githubusercontent.com/assets/7907/8761061/64000700-2d35-11e5-9591-4aecb3e2b0af.png)

After uploading the `.tcx` file manually, however, it does appear:

![garmin-connect-after](https://cloud.githubusercontent.com/assets/7907/8761076/83ac1a26-2d35-11e5-8432-680fbc734b0c.png)

**Comment by mehrar** [comment]
Same Issue

**Comment by kootox** [comment]
Just posted a Pull request fixing the problem (https://github.com/braiden/python-ant-downloader/pull/67).

My fork is working at the moment (https://github.com/kootox/python-ant-downloader)

**Comment by braiden** [comment]
Merged, Thank you @kootox !
