### ISSUE TITLE
Issue trying to pair device

### ISSUE THREAD

**Issue by aremai** [braiden/python-ant-downloader#73]
Hi,

I recently had to re-install my laptop (I'm running Ubuntu 16.04 LTS) and followed your guide to install ant-downloader.
As soon as I'm running

`# sudo ant-downloader`

I'm receiving the following error:
`Traceback (most recent call last):
  File "/usr/local/bin/ant-downloader", line 9, in <module>
    load_entry_point('python-ant-downloader==13.2.24', 'console_scripts', 'ant-downloader')()
  File "/usr/local/lib/python2.7/dist-packages/antd/main.py", line 75, in downloader
    host = antd.cfg.create_antfs_host()
  File "/usr/local/lib/python2.7/dist-packages/antd/cfg.py", line 118, in create_antfs_host
    host = antfs.Host(create_ant_session(), keys)
  File "/usr/local/lib/python2.7/dist-packages/antd/cfg.py", line 105, in create_ant_session
    session = ant.Session(create_ant_core())
  File "/usr/local/lib/python2.7/dist-packages/antd/cfg.py", line 101, in create_ant_core
    return ant.Core(create_hardware())
  File "/usr/local/lib/python2.7/dist-packages/antd/cfg.py", line 92, in create_hardware
    return hw.UsbHardware(id_vendor, id_product, bulk_endpoint)
  File "/usr/local/lib/python2.7/dist-packages/antd/hw.py", line 48, in __init__
    for dev in usb.core.find(idVendor=id_vendor, idProduct=id_product, find_all=True):
AttributeError: 'module' object has no attribute 'find'
`

Any ideas what I'm doing wrong here?

Thanks a lot in advance and please keep up the excellent work!!

**Comment by braiden** [comment]
Either you do not have pyusb installed or you have an older version (most
debian based distros still have an older version of pysub)?

You can find pyusb install instructions here:
https://github.com/walac/pyusb

**Comment by aremai** [comment]
It's interesting those all those dependencies are already met...

`drwxr-sr-x  2 root staff 4096 Dez  5 09:07 antd/
drwxr-sr-x  2 root staff 4096 Dez  5 09:06 distribute-0.7.3-py2.7.egg-info/
drwxr-sr-x  2 root staff 4096 Dez  5 09:03 get-0.0.0.egg-info/
drwxr-sr-x  6 root staff 4096 Dez  5 09:02 lxml/
drwxr-sr-x  2 root staff 4096 Dez  5 09:02 lxml-3.6.4.dist-info/
drwxr-sr-x  2 root staff 4096 Dez  5 09:03 post-0.0.0.egg-info/
drwxr-sr-x  2 root staff 4096 Dez  5 01:20 poster/
drwxr-sr-x  2 root staff 4096 Dez  5 09:06 poster-0.8.1.egg-info/
drwxr-sr-x  2 root staff 4096 Dez  5 09:03 public-0.0.0.egg-info/
drwxr-sr-x  2 root staff 4096 Dez  5 09:07 python_ant_downloader-13.2.24.egg-info/
drwxr-sr-x  2 root staff 4096 Dez  5 09:00 pyusb-1.0.0.egg-info/
drwxr-sr-x  2 root staff 4096 Dez  5 09:03 query_string-0.0.0.egg-info/
drwxr-sr-x  2 root staff 4096 Dez  5 09:03 request-0.0.0.egg-info/
drwxr-sr-x  2 root staff 4096 Dez  5 09:03 setupfiles-0.0.0.egg-info/
drwxr-sr-x  2 root staff 4096 Dez  5 01:20 tests/
drwxr-sr-x  3 root staff 4096 Dez  5 01:53 usb/
`

Is version 1.0.0 of pyusb too old?
those are part of the dist-packages of python2.7

**Comment by aremai** [comment]
Ok, it's working now...for some reason the installation of my pre-requisites seemed a bit messed up.

I uninstall pyusb and python_ant_downloader
and then ran

`sudo pip install --pre pyusb`
andn
`sudo pip install python_ant_downloader`

now it works like a charm again :)
